config/routes.rb
Rails.application.routes.draw do
  get '/instructs', to: 'static_pages#instructs'
  resources :grades
  resources :enrolls
  get 'sessions/new'
  root 'static_pages#home'
  resources :courses
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :assignments
  resources :grades do
    collection do
      put :update_multiple
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  has_many :grade

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  def create
    @assignment = Assignment.new(assignment_params)
    @grade = Grade.where(@assignment.id)
    respond_to do |format|
      if @assignment.save
        Enroll.where(course_id: @assignment.course_id).each do |enroll|
          Grade.create(user_id: enroll.user.id, assignment_id: @assignment.id) 
        end
        format.html { redirect_to @assignment.course, notice: 'assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_multiple
    Grade.update(params[:grades].keys, params[:grades].values)
    redirect_to '/courses'
  end

  def new
    @assignment = Assignment.new
    @course = params[:course_id]
  end

  def destroy
    Grade.where(assignment_id: @assignment.id).destroy_all
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to @assignment.course, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @grades = @assignment.grade.all
  end

  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment.course, notice: 'assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end


      private

      def set_assignment
        @assignment = Assignment.find(params[:id])
      end

      def assignment_params
        params.require(:assignment).permit(:full_credit, :name, :course_id)
      end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<b><%= assignment.name %> </b>: 

<% if @course.user.id != current_user.id %>
<%= assignment.grade.find_by(user_id: current_user.id)  ?  assignment.grade.find_by(user_id: current_user.id).earned_credit :  "--"  %>  
<% end %>
/ <%= assignment.full_credit %>
(Average 
<% if assignment.grade.count > 0 %>
<%= assignment.grade.average(:earned_credit).to_i %> 
<% else %>
--
<% end %>
/ <%= assignment.full_credit %> )
<% if @course.user.id == current_user.id %>
 <%= link_to "Edit ", edit_assignment_path(assignment, course_id: @course.id)%>
 <%= link_to "Delete", assignment, method: :delete, data: { confirm: "You sure?" } %> 
<% end %> 
 <%= link_to "Graph ", assignment_path(assignment) %>
<br>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% assignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: 'Assignemnt #' + params[:assignment].to_s %>
  </div>

  <div class="field">
    <%= form.hidden_field :course_id %>
    <%= form.hidden_field :course_id, :value =>  params[:course_id]%>
  </div>

  <div class="field">
    <%= form.label :full_credit %>
    <%= form.number_field :full_credit, placeholder: 100  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>


<% if false %>
  <%= form_with(model: @assignment, local: true) do |form| %>
    <% Enroll.where(course_id: @assignment.course_id).each do |enroll| %>
      <%= enroll.user.name  %> 
      <div class="field">
        <%= form.number_field @assignment.grade.find_by(user_id: current_user.id).earned_credit %>
      </div>
      <%= @assignment.grade.find_by(user_id: enroll.user.id)  ?  @assignment.grade.find_by(user_id: current_user.id).earned_credit :  ""  %> <br>

    <% end %>
  <% end %>
<% end %>
<% if @assignment.grade.count > 0 %>
<%= form_tag update_multiple_grades_path, method: :put do %>
  <% @assignment.grade.all.each do |f| %>
    <%= hidden_field_tag "grade_ids[]", f.id %>
    <%= fields_for "grade[]", f do |form| %>
      <div class="field">
        <%= form.label f.user.name %>
        <%= form.number_field :earned_credit %>
      </div>
    <% end %>
  <% end %>
    <div class="actions">
      <%= submit_tag "Update Grades" %>
    </div>
  <% end %>
<% end %>
<% if false %>
  <%= render 'grades/form', grade: @assignment.grade.find(2) %>
  <%= @assignment.grade.all.count %>
<% end %>

<%= link_to 'Back', @assignment.course %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>                                                    
<%= render 'form', assignment: @assignment %>

app/views/assignments/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<p>
  <strong>Assignment:</strong>
  <%= @assignment.name %>
</p>

<%= line_chart Grade.where(assignment_id: @assignment.id).where.not(earned_credit: nil).group(:earned_credit).count, round:1, messages: {empty: "No grades yet"}   %>