config/routes.rb
Rails.application.routes.draw do
  get '/instructs', to: 'static_pages#instructs'
  resources :grades
  resources :enrolls
  get 'sessions/new'
  root 'static_pages#home'
  resources :courses
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :assignments
  resources :grades do
    collection do
      put :update_multiple
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enroll.rb
class Enroll < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/enrolls_controller.rb
class EnrollsController < ApplicationController
  before_action :set_enroll, only: [:show, :edit, :update, :destroy]

  # GET /enrolls
  # GET /enrolls.json
  def index

    @enrolls = Enroll.where(user_id: current_user.id)
    @courses = Course.where(user_id: current_user.id)
  end

  # GET /enrolls/1
  # GET /enrolls/1.json
  def show
  end

  # GET /enrolls/new
  def new
    @enroll = Enroll.new
  end

  # GET /enrolls/1/edit
  def edit
  end

  # POST /enrolls
  # POST /enrolls.json
  def create
    @enroll = Enroll.new(enroll_params)
    @enroll.user_id = current_user.id if current_user

    respond_to do |format|
      if @enroll.save
        Assignment.where(course_id: @enroll.course_id).each do |assignment|
          Grade.create(user_id: current_user.id, assignment_id: assignment.id)
      end
        format.html { redirect_to @enroll.course, notice: 'Enroll was successfully created.' }
        format.json { render :show, status: :created, location: @enroll }
      else
        format.html { render :new }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolls/1
  # PATCH/PUT /enrolls/1.json
  def update
    respond_to do |format|
      if @enroll.update(enroll_params)
        format.html { redirect_to @enroll, notice: 'Enroll was successfully updated.' }
        format.json { render :show, status: :ok, location: @enroll }
      else
        format.html { render :edit }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolls/1
  # DELETE /enrolls/1.json
  def destroy
        Assignment.where(course_id: @enroll.course_id).each do |assignment|
          Grade.where(user_id: @enroll.user.id, assignment_id: assignment.id).destroy_all
      end
    @enroll.destroy
    respond_to do |format|
      format.html { redirect_to @enroll.course, notice: 'Student Unenrolled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enroll
      @enroll = Enroll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enroll_params
      params.permit(:user_id, :course_id)
    end
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/views/enrolls/_form.html.erb
<%= form_with(model: enroll, local: true) do |form| %>
  <% if enroll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enroll.errors.count, "error") %> prohibited this enroll from being saved:</h2>

      <ul>
        <% enroll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id , placeholder: 'Course ID'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrolls/edit.html.erb
<h1>Editing Enroll</h1>

<%= render 'form', enroll: @enroll %>

<%= link_to 'Show', @enroll %> |
<%= link_to 'Back', enrolls_path %>

app/views/enrolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrolled</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Instructor</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolls.each do |enroll| %>
      <tr>
        <td><%= enroll.course.name %></td>
        <td><%= enroll.course.user.name %></td>
        <td><%= Grade.where(user_id: current_user.id, assignment_id: enroll.course.assignments).sum(:earned_credit) %> / 
        <%= enroll.course.assignments.sum(:full_credit) %></td>

        <td><%= link_to 'Show', enroll.course %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Enroll', courses_path %>

app/views/enrolls/new.html.erb
<h1>New Enroll</h1>

<%= render 'form', enroll: @enroll %>

<%= link_to 'Back', enrolls_path %>

app/views/enrolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @enroll.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enroll.course_id %>
</p>

<%= link_to 'Edit', edit_enroll_path(@enroll) %> |
<%= link_to 'Back', enrolls_path %>