config/routes.rb
Rails.application.routes.draw do
  get '/instructs', to: 'static_pages#instructs'
  resources :grades
  resources :enrolls
  get 'sessions/new'
  root 'static_pages#home'
  resources :courses
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :assignments
  resources :grades do
    collection do
      put :update_multiple
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @assignments = @course.assignments
    @enrolls = @course.enrolls
    @earned_credit = Grade.where(user_id: current_user.id, assignment_id: @assignments).sum(:earned_credit)
    @full_credit = @assignments.sum(:full_credit)
    @course_score = (@earned_credit.to_f / (@full_credit.to_f + 0.0001)*100).to_i 
    @scores ||= []
    @enrolls.each do |enroll|
      @scores <<  Grade.where(user_id: enroll.user.id, assignment_id: enroll.course.assignments).sum(:earned_credit) 
    end
    @freq = score(@scores)


  end

  def score( array )
    array.each_with_object(Hash.new(0)){|key,hash| hash[key] += 1}
  end
  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id if current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Course</th>
      <th>Instructor</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.id %></td>
        <td><%= course.name %></td>
        <td><%= course.user.name %></td>
        <td>
          <% if current_user.id == course.user.id || Enroll.find_by(course_id: course.id, user_id: current_user.id )%> --- <% else %>
          <%= link_to 'Enroll', {:controller => 'enrolls', :action => 'create', :course_id => course.id, :user_id => current_user.id}, {:method => :post}  %></td>
      <% end %>
        <% if current_user.id == course.user.id %>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h1>
  <strong>Course:</strong>
  <%= @course.name %>
</h1>

<h3>
  <strong>Instructor:</strong>
  <%= @course.user.name %>
  <%= link_to "(Profile)", user_path(@course.user.id) %>
</h3>

<p>
<% if @course.user.id != current_user.id %>
  <b> Course Score: </b> <%= @course_score %> % <br>
<b> Earned Credit: </b> <%= @earned_credit %> <br> 
<% end %>
<b> Full Credit: </b> <%= @full_credit %></br>
</p>

<h3> Assignments (<%= @assignments.count %>): </h3>
<%= render @assignments %>

<br>
<br>
<% if current_user.id == @course.user.id %>
<%= link_to 'Add Assignment', new_assignment_path(:course_id => @course.id, :assignment => @course.assignments.count) %> 
<% end %>
<h3> Students (<%= @enrolls.count %>): </h3>

    <% @enrolls.each do |enroll| %>
      <%= enroll.user.name  %> 
<% if @course.user.id == current_user.id %>
      <%= Grade.where(user_id: enroll.user.id, assignment_id: enroll.course.assignments).sum(:earned_credit) %> / 
      <%= enroll.course.assignments.sum(:full_credit) %> 
      <td><%= link_to 'Unenroll', enroll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      | <%= link_to 'Profile', user_path(enroll.user.id) %> <br>  


    <% end %>
    <br>
<% if @course.user.id == current_user.id %>
    <%= link_to 'Edit Course Name', edit_course_path(@course) %> <br>
  <% end %>
  <% if false %>
  <%= line_chart @scores.count, round:1, messages: {empty: "No grades yet"}   %>
<% end %>
<br>
<%= line_chart @freq, messages: {empty: "No grades yet"}   %>